###################################################################
#MRT SIMULATION                                                   #
#                                                                 #
#For the project: "Using Dynamic, Data-Driven Simulations         #
#On MRT Passenger Traffic Data For Optimizing                     #
#Service Performance Strategies                                   #
#                                                                 #
#By Dominic B Dayta                                               #
#February, 2018                                                   #
#                                                                 #
###################################################################

#The entire model, which uses 100 iterations, takes an average of 
#21 hours to model the five train, eight train, and twenty train scenario
#More iterations might be ideal to further regularize the behavior of
#the random component, but 1000 iterations for example would take
#upwards of a week to complete. For reasons of time limitation
#we made do with 100.

#for trial runs, one can open the function arrival_simulation() and change the number of iterations
#to 1, 2, up to 5, any of which should not take any more than an hour to run

#the speed can be modified within the function train_arrivals(), under the variable v

library(sqldf)

#set the working directory to where the MRT1214 dataset can be found
#this is a modified version of the 2012-2014 MRT Passenger traffic data found on
#data.gov.ph

setwd("E:/MRT Simulation Project/R Codes and Datasets")


##################################################################
#what follows are a series of function definitions that will be necessary for the
#execution of the entire simulation

train_arrivals<-function(iteration,trains,parking,stations,deployment_interval){  
  distance<-rep(1300,times=12)
  maxarrivals<-rep(0,times=trains) #catch the maximum arrival times per train
  v<-750 #speed in meters per minute of Singapore MRT is 1333 meters per minute or 80kph
  #MRT Philippines default is at 45 kilometers per hour, or 750 meters per minute
  k<-1
  K<-100
  j<-1 #counter
  ophours<-1020 #the length in minutes of operations
  
  arrivals<-as.data.frame(matrix(rep(0,times=trains*(stations+2)*K),nrow=trains*K,ncol=(stations+2)))
  colnames(arrivals)<-c("Timetables","Train","S1","S2","S3","S4","S5","S6","S7","S8","S9","S10","S11","S12","S13")
  
  while(maxarrivals[trains]<=ophours){
    for(tau in 1:trains){
      
      arrivals[j,1]<-k
      arrivals[j,2]<-tau
      
      for(s in 1:stations){
        
        set.seed(iteration*k*tau*s)
        
        #initialize the train arrivals for the first time table
        if(k==1){
          if(tau==1 && s==1){
            arrivals[j,2+s]<-0 #station collects passengers for 5 minutes before it deploys its first train
          } else if(tau>1 && s==1){
            arrivals[j,2+s]<-arrivals[j-1,2+s]+parking+deployment_interval
          } else{
            arrivals[j,2+s]<-max(c((round(arrivals[j,2+s-1]+parking+distance[s-1]/v+rnorm(1,mean=0,sd=1))),
                                   (arrivals[j-1,2+s]+parking+1)))
            
            #when the train reaches the last station catch the arrival time into the maxarrivals vector
            if(s==13) maxarrivals[tau]<-arrivals[j,2+s]
          }
        } else if(k>1){
          if(tau==1 && s==1){
            arrivals[j,2+s]<-max(c(round(maxarrivals[tau]+stations*parking+rnorm(1,mean=(sum(distance)/v),sd=sqrt(stations))),
                                   (arrivals[j-1,2+s]+parking+1)))
          } else if(tau>1 && s==1){
            arrivals[j,2+s]<-max(c(round(maxarrivals[tau]+stations*parking+rnorm(1,mean=(sum(distance)/v),sd=sqrt(stations))),
                                   (arrivals[j-1,2+s]+parking+1)))
          } else{
            arrivals[j,2+s]<-max(c((round(arrivals[j,2+s-1]+parking+distance[s-1]/v+rnorm(1,mean=0,sd=1))),
                                   (arrivals[j-1,2+s]+parking+1)))
            
            #when the train reaches the last station catch the arrival time into the maxarrivals vector
            if(s==13) maxarrivals[tau]<-arrivals[j,2+s]
          }
        }
        
      }
      j<-j+1
    }
    
    k=k+1
  }
  
  #delete extra rows from the timetable
  arrivals<-subset(arrivals,Timetables>0)
  return(arrivals)
}

arrives<-function(time1,time2,station,year,iterate){
  #load passenger entry data
  entry<-subset(read.csv2("MRT1214.csv",sep=","),ACTIVITY="ENTRY",YEAR=paste(year))
  
  #get the arrival time from the train table
  for(j in 0:24){
    if(time2<=60*j){
      arrival_time<-j
      break
    }
  }
  
  #create a cumulative density function for the arrivals
  #really part of what slows the code down is the plot generated by the hist() function
  #but I keep them in the code so I know the simulation is running
  #(My computer is antiquated so this is important during the debug phase)
  h<-hist(as.numeric(subset(entry,END_HOUR==paste(arrival_time),select=paste(station))[[1]]),main=paste("Distribution of Arrivals, ",station,sep=""),xlab="Number of Arrivals",freq=FALSE)
  cumdensity<-rep(0,NROW=h$counts)
  for(j in 1:NROW(h$counts)){cumdensity[j]<-sum(h$counts[1:j])/sum(h$counts)}
  cdf<-cbind(h$breaks[2:NROW(h$breaks)],cumdensity)
  #plot(x=h$breaks[2:NROW(h$breaks)],y=cumdensity,type="s",xlab="Number of arrivals within an hour",ylab="Cumulative Density",
       #main=paste("Cumulative Density of Arrivals",station))
  
  #use inverse sampling by taking a random number from the uniform(0,1) distribution
  #then catch the passenger arrival number with a corresponding cumulative density
  sampled<-runif(1,0,1)
  for(j in 1:nrow(cdf)){
    if(sampled<=cdf[j,2]){
      maxarrival<-cdf[j,1]
      if(j==1) meanarrival<-cdf[j,1]/2 else meanarrival<-(cdf[j,1]+cdf[j-1,1])/2 
      break
    }  
  }

  set.seed(round(iterate*time2*time1,digits=0))
  passengers<-rpois(1,{meanarrival/60}*{time2-time1})
  
  return(passengers)  
}

arrival_simulation<-function(trains,parking,stations,deployment_interval){
  begin<-Sys.time()
  
  #replace iterations here
  for(iterate in 1:100){
    #generate one iteration of the train time table  
    arrival<-train_arrivals(iterate,trains,2,13,5)
    
    #determine the number of iterations that have happened
    nth_iterate<-rep(iterate,times=nrow(arrival))
    
    #indicate the iteration count in the arrival matrix
    arrival<-cbind(nth_iterate,arrival)
    colnames(arrival)[1]<-"Iteration"
    if(iterate==1) iterated_arrivals<-arrival else iterated_arrivals<-rbind(iterated_arrivals,arrival)
    
    #generate matrix of proportion of southbound arrivals per station
    southbound<-c(1,0.95,0.95,0.95,0.7,0.6,0.5,0.4,0.3,0.05,0.05,0.05,0)
    
    #generate table of passengerarrivals in each station
    passenger_entry<-matrix(0,ncol=13,nrow=nrow(arrival))
    stations<-c("NORTH","QUEZON","KAMUNING","CUBAO","SANTOLAN","ORTIGAS","SHAW","BONI","GUADALUPE","BUENDIA","AYALA","MAGALLANES","TAFT")
    for(station in 1:13){
      for(k in 1:nrow(arrival)){
        if(k==1){
          passenger_entry[k,station]<-round(arrives(0,240+arrival[k,3+station]+parking,stations[station],2014,iterate)*southbound[station],digits=0)
        } else{
          passenger_entry[k,station]<-round(arrives(240+arrival[k-1,3+station]+parking,240+arrival[k,3+station]+parking,stations[station],2014,iterate)*southbound[station],digits=0)
        }
      }
    }
    passenger_entry<-cbind(arrival[,1:3],passenger_entry)
    passenger_entry<-cbind(nth_iterate,passenger_entry)
    colnames(passenger_entry)[1]<-"Iteration"
    if(iterate==1) it_passenger_entry<-passenger_entry else it_passenger_entry<-rbind(it_passenger_entry,passenger_entry)
    
    
    #get the cumulative arrivals
    cumulative_arrival<-matrix(0,ncol=13,nrow=nrow(arrival))
    for(station in 1:13){
      for(j in 1:nrow(arrival)){
        if(j==1){
          cumulative_arrival[j,station]<-passenger_entry[j,4+station]
        } else{
          cumulative_arrival[j,station]<-passenger_entry[j,4+station]+cumulative_arrival[j-1,station]
        }
      }
    }
    cumulative_arrival<-cbind(arrival[,1:3],cumulative_arrival)
    cumulative_arrival<-cbind(nth_iterate,cumulative_arrival)
    if(iterate==1) it_cumulative_arrival<-cumulative_arrival else it_cumulative_arrival<-rbind(it_cumulative_arrival,cumulative_arrival)
    
    #simulate the arrival of a single train across rows
    queue<-matrix(0,ncol=13,nrow=nrow(arrival))
    #the following is the arrival of the trains when all trains service all the stations
    for(k in 1:nrow(arrival)){
      #a vector that gives the number of people currently riding the train
      #MRT reports a combined sitting and standing capacity of 1180 people
      #the free space left will then be given by capacity(t)=1180-load(t)
      load<-rep(0,times=13)

      #below is a vector that states the percentage of the train's load that will exit at a given station
      exit<-c(0,0,0.01,0.05,0.2,0.3,0.2,0.2,0.4,0.4,0.2,1)
      
      for(station in 1:13){
        #the maximum number of people that can board the train is the smallest between
        #the number of people waiting on the station and
        #the maximum capacity left of the current train
        
        
        #capacity at station is capacity at previous station-number of exits
        if(station>1) load[station]<-load[station-1]*(1-exit[station])
        
        if(k==1){
          people_board<-min(passenger_entry[k,4+station],round(0.9*(1180-load[station]),digits=0))
          
          #and the number of people left on queue is
          #queue(t)=queue(t-1)+arrivals(t-1,t)-board(t)
          #but on the first deployment, the queue(t-1)
          queue[k,station]<-passenger_entry[k,4+station]-people_board
          
        } else{
          #capacity at station is capacity at previous station - number of exits
          people_board<-min(queue[k-1,station]+passenger_entry[k,4+station],round(0.9*(1180-load[station]),digits=0))
          queue[k,station]<-queue[k-1,station]+passenger_entry[k,4+station]-people_board
        }
        
        #the load of the train is then increased by the number of people that board
        load[station]<-load[station]+people_board
      }
    }
    queue<-cbind(arrival[,1:3],queue)
    queue<-cbind(nth_iterate,queue)
    if(iterate==1) it_queue<-queue else it_queue<-rbind(it_queue,queue)

  }
  
  duration<-begin-Sys.time()
  return(list("train_arrivals"=iterated_arrivals,
              "passenger_entry"=it_passenger_entry,
              "cum_passenger_arrivals"=it_cumulative_arrival,
              "queue"=it_queue,
              "computation_time"=duration))
}

#create a trains only simulation (to simulate the waiting time when n trains are deployed)
#remove passenger simulation to cut down on computation time

trainsonly<-function(trains,parking,stations,deployment_interval){
  begin<-Sys.time()
  
  for(iterate in 1:100){
    #generate one iteration of the train time table  
    arrival<-train_arrivals(iterate,trains,2,13,5)
    
    #determine the number of iterations that have happened
    nth_iterate<-rep(iterate,times=nrow(arrival))
    
    #indicate the iteration count in the arrival matrix
    arrival<-cbind(nth_iterate,arrival)
    colnames(arrival)[1]<-"Iteration"
    if(iterate==1) iterated_arrivals<-arrival else iterated_arrivals<-rbind(iterated_arrivals,arrival)
    
  }
  
  duration<-begin-Sys.time()
  return(list("train_arrivals"=iterated_arrivals,
              "computation_time"=duration))
}

##################################################################
#now we run the model assuming there are 5 trains, eight trains, and twenty trains

five_trains<-arrival_simulation(5,2,13,5)
eight_trains<-arrival_simulation(8,2,13,5)
twenty_trains<-arrival_simulation(20,2,13,5)


##################################################################
#the rest are code blocks designed to process the data produced from the models
#to generate results on: 1) average waiting time between train arrivals and
#average queue depth in each station assuming there are 5 trains, 8 trains, and 20 trains

{
  #this entire code block finds the average waiting time on
  #platform for the next train given the number of functioning trains
  
  
  #below are the matrices to catch the average, a well as the 2.5th and 97.5th quantiles of the
  #simulated train inter-arrival times (in order to catch the 95% empirical confidence interval)
  avg_arrivals<-as.data.frame(matrix(0,nrow=100,ncol=14))
  low_arrivals<-as.data.frame(matrix(0,nrow=100,ncol=14))
  high_arrivals<-as.data.frame(matrix(0,nrow=100,ncol=14))
    
  for(j in 1:20){
    
    arrivals<-trainsonly(j,2,13,5)$train_arrivals
    
    colnames(avg_arrivals)<-c("Trains","S1","S2","S3","S4","S5","S6","S7","S8","S9","S10","S11","S12","S13")
    colnames(low_arrivals)<-c("Trains","Low_S1","Low_S2","Low_S3","Low_S4","Low_S5","Low_S6","Low_S7","Low_S8","Low_S9","Low_S10","Low_S11","Low_S12","Low_S13")
    colnames(high_arrivals)<-c("Trains","High_S1","High_S2","High_S3","High_S4","High_S5","High_S6","High_S7","High_S8","High_S9","High_S10","High_S11","High_S12","High_S13")
    vec<-rep(0,times=NROW(arrivals))
    
    for(k in 1:13){
      
      for(i in 1:NROW(arrivals)){
        if(arrivals[i,2]==1 && arrivals[i,3]==1){
          vec[i]<-0
        } else{
          vec[i]<-arrivals[i,3+k]-arrivals[i-1,3+k]
        }
      }
      
      avg_arrivals[j,1]<-j
      avg_arrivals[j,1+k]<-mean(vec)
      
      low_arrivals[j,1]<-j
      low_arrivals[j,1+k]<-quantile(vec,probs=0.025)
      
      high_arrivals[j,1]<-j
      high_arrivals[j,1+k]<-quantile(vec,probs=0.975)
    }
    
    
  }
  
  avg_arrivals<-subset(avg_arrivals,Trains>0)
  low_arrivals<-subset(low_arrivals,Trains>0)
  high_arrivals<-subset(high_arrivals,Trains>0)
  
  plot(avg_arrivals$Trains,avg_arrivals$S1,col="blue",
       ylab="Waiting Time",xlab="Number of Functioning Trains",
       main="Average Waiting Time (North Avenue)",sub="In Minutes")
  par(new=TRUE)
  lines(avg_arrivals$Trains,avg_arrivals$S2,col="green")
  plot(avg_arrivals$Trains,avg_arrivals$S3,col="black")
  write.csv(cbind(cbind(avg_arrivals,low_arrivals),high_arrivals),"45kph - avg_waitingtime.csv")
}

{
  #this code block gets average queue depth for five, eight and twenty trains
  #for visualization on excel
  
  q_fivetrains<-five_trains$queue
  q_eighttrains<-eight_trains$queue
  q_twentytrains<-twenty_trains$queue
  colnames(q_fivetrains)[5:17]<-c("S1","S2","S3","S4","S5","S6","S7","S8","S9","S10","S11","S12","S13")
  colnames(q_eighttrains)[5:17]<-c("S1","S2","S3","S4","S5","S6","S7","S8","S9","S10","S11","S12","S13")
  colnames(q_twentytrains)[5:17]<-c("S1","S2","S3","S4","S5","S6","S7","S8","S9","S10","S11","S12","S13")
  
  queue5<-sqldf("Select timetables,train,avg(S1) as S1,
                avg(S2) as S2,
                avg(S3) as S3,
                avg(S4) as S4,
                avg(S5) as S5,
                avg(S6) as S6,
                avg(S7) as S7,
                avg(S8) as S8,
                avg(S9) as S9,
                avg(S10) as S10,
                avg(S11) as S11,
                avg(S12) as S12,
                avg(S13) as S13
                from q_fivetrains
                group by timetables,train")
  
  queue8<-sqldf("Select timetables,train,avg(S1) as S1,
                avg(S2) as S2,
                avg(S3) as S3,
                avg(S4) as S4,
                avg(S5) as S5,
                avg(S6) as S6,
                avg(S7) as S7,
                avg(S8) as S8,
                avg(S9) as S9,
                avg(S10) as S10,
                avg(S11) as S11,
                avg(S12) as S12,
                avg(S13) as S13
                from q_eighttrains
                group by timetables,train")
  
  queue20<-sqldf("Select timetables,train,avg(S1) as S1,
                avg(S2) as S2,
                avg(S3) as S3,
                avg(S4) as S4,
                avg(S5) as S5,
                avg(S6) as S6,
                avg(S7) as S7,
                avg(S8) as S8,
                avg(S9) as S9,
                avg(S10) as S10,
                avg(S11) as S11,
                avg(S12) as S12,
                avg(S13) as S13
                from q_twentytrains
                group by timetables,train")
  
  write.csv(queue5,"45kph - queue for 5 trains.csv",row.names=FALSE)
  write.csv(queue8,"45kph - queue for 8 trains.csv",row.names=FALSE)
  write.csv(queue20,"45kph - queue for 20 trains.csv",row.names=FALSE)
}
